### ISSUE TITLE
pfsensible.core.nat_port_forward Interface:Network - What's the proper format?

### ISSUE THREAD

**Issue by tvories** [pfsensible/core#10]
On the rules I have specified manually, the `Destination` type is `WAN address`.  When I define the same rule in my pfsensible role, I can only figure out how to get `WAN net` to work.

Here is the code:

```yaml
- name: Apply nat port forward rules
  pfsensible.core.nat_port_forward:
    descr: Test nat rule
    interface: wan
    source: any
    destination: WAN:48222 # <--- This field is the issue
    target: 192.168.2.100:48223
    associated_rule: pass
    state: present
```

The code gives me the result:
![image](https://user-images.githubusercontent.com/13934524/75812969-66187d00-5d4c-11ea-813c-8601ac6ea2cd.png)

My manually defined rule looks like:
![image](https://user-images.githubusercontent.com/13934524/75813014-7e889780-5d4c-11ea-94a5-a223b2a2ac2a.png)

What is the proper format to set the destination to `Wan address` instead of `Wan net`?
