### ISSUE TITLE
[pfsense_ca] Add ability to create a certificate authority, not just import one

### ISSUE THREAD

**Issue by samuel-emrys** [pfsensible/core#135]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to create a certificate authority rather than just import one, as is supported by the pfSense web gui. This would allow a fresh installation to easily be managed without manual intervention to configure certificates.

**Describe the solution you'd like**
The following syntax would create a certificate authority:

```yaml
- name: Create CA
  pfsensible.core.pfsense_ca:
    name: root-ca
    method: internal
    trust_store: true
    randomize_serial: true
    key_type: rsa
    key_length: 2048
    digest: sha256
    lifetime: 3650
    common_name: internal-ca
    country: us
    state: texas
    city: austin
    org: my org
    org_unit: my department
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
