### ISSUE TITLE
[pfsense_dns_resolver] active_interface can't bind to virtual ip address

### ISSUE THREAD

**Issue by huwany** [pfsensible/core#136]
**Describe the bug**
the active_interface can't bind to virtual ip address.

**Expected behavior**
the active_interface can be bound to virtual ip address, e.g 192.168.1.5 or ip's description dns_ip.

**Playbook**
Please paste a minimal playbook to reproduce the issue:
```
    - name: Enable DNS Resolver with some options
      pfsensible.core.pfsense_dns_resolver:
        state: present
        dnssec: false
        regdhcp: false
        regdhcpstatic: true
        forwarding: true
        forward_tls_upstream: false
        active_interface: "192.168.1.5"
```

**Output**
Please paste the ansible output run with `-vv`:
```
TASK [Enable DNS Resolver with some options] ***********************************************************************
task path: /opt/pfsense/ansible/main.yaml:220
fatal: [cnhz]: FAILED! => {"changed": false, "msg": "if_descr, 192.168.1.5, is not exist"}
```

**Environment**
- What version of pfsensible.core?
  - 0.6.1
- What version of ansible?
  - 2.15.8
- What version of pfSense?
  - 2.7.2

**Additional context**
