### ISSUE TITLE
Unchecking/disabling ldap_allow_unauthenticated odes not work

### ISSUE THREAD

**Issue by TRoc81** [pfsensible/core#139]
**Describe the bug**
I am trying to disable the _ldap_allow_unauthenticated_ option, which is enabled by default when creating a new LDAP authentication server.
I can re-enable it after manually disabling the option.
Same with _ldap_rfc2307_, but this option is not enabled by default.
I can enable both by setting them to _true_ in the playbook, but cannot disable them by setting them to _false_ in the playbook.

There is no error when running the playbook. 
I tried FALSE, false, False, "FALSE", "false" and "False".

**Expected behavior**
Options will either be checked when setting them to true or unchecked when setting them to false in the playbook.

**Playbook**
Please paste a minimal playbook to reproduce the issue:
```
    - name: Add adservers authentication server
      pfsensible.core.pfsense_authserver_ldap:
        name: AD
        host: adserver.example.com
        port: 636
        transport: ssl
        scope: subtree
        authcn: cn=users
        basedn: dc=example,dc=com
        binddn: cn=bind,ou=Service Accounts,dc=example,dc=com
        bindpw: "password"
        attr_user: samAccountName
        attr_member: memberOf
        attr_groupobj: group
        ldap_allow_unauthenticated: false
        state: present
```

**Output**
Please paste the ansible output run with `-vv`:
```
PLAYBOOK: test.yaml **************************************************************************************************************************************************************************************
1 plays in test.yaml

PLAY [create ldap auth server] ***************************************************************************************************************************************************************************

TASK [Add adservers authentication server] ***************************************************************************************************************************************************************
task path: /home/ubuntu/playbooks/pfsense/test.yaml:8
changed: [fw01-a-pfsensetest] => {"changed": true, "commands": ["create authserver_ldap 'AD'"], "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY RECAP ***********************************************************************************************************************************************************************************************
fw01-a-pfsensetest         : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

**Environment**
- What version of pfsensible.core? 
0.6.2
- What version of ansible? 
2.16.3
- What version of pfSense? 
2.7.2
