### ISSUE TITLE
Issue connecting to pfSense

### ISSUE THREAD

**Issue by ericsysmin** [pfsensible/core#14]
Any idea on why I'm getting a invalid `-c` option error
```
<10.79.109.138> SSH: EXEC sshpass -d43 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'User="admin"' -o ConnectTimeout=10 -o ControlPath=/Users/****/.ansible/cp/d05d73dcc1 10.79.109.138 '/bin/sh -c '"'"'echo ~admin && sleep 0'"'"''
<10.79.109.138> (2, b'', b'Bad -c option\n')
```

```
---
- hosts: pfsense
  become: true
  gather_facts: false
  tasks:
    - name: Add operator user
      pfsensible.core.user:
        name: "{{ item.username }}"
        descr: "{{ item.full_name }}"
        scope: user
        priv: [ 'user-shell-access' ]
        authorizedkeys: "{{ item.authorized_key|b64encode }}"
      loop: "{{ ops_users }}"
```
