### ISSUE TITLE
How to use pfsensible.core.pfsense_rule gateway option

### ISSUE THREAD

**Issue by sez76** [pfsensible/core#144]
**Is your feature request related to a problem? Please describe.**
I I have try to use the gateway option with pfsense_rule but I have error message : 
```"fatal: [pfsense]: FAILED! => {"changed": false, "msg": "Gateway \"WANGW\" does not exist or does not match target rule ip protocol."}" I don't enderstant because my gateway exist.```

My tast :
```yml
- name: internet access rules
  pfsensible.core.pfsense_rule:
    name: internet access
    action: pass
    interface: LAN1
    ipprotocol: inet
    protocol: tcp
    source: NET:LAN1
    # source_port: any
    destination: any
    # destination_port: any
    gateway: WANGW
    before: bottom
    state: present
```

![Capture d’écran 2024-10-23 161345](https://github.com/user-attachments/assets/ea4d01bd-5be7-442b-874d-75afb6211831)

any idea ?
