### ISSUE TITLE
pfsense_cert should fail for internal certificates if no internal CA is available

### ISSUE THREAD

**Issue by DanielRaapDev** [pfsensible/core#165]
**Describe the bug**
The Ansible module `pfsense_cert` runs smoothly when asked to create an internal (user) certificate but no internal CA is available. As a certificate is requested by the Ansible code the module should fail if not able to do so. Currently the pfSense will get an entry in the list of certificates with a name as requested. But that entry has no X.509 certificate.

**Expected behavior**
If no internal CA (a CA with a key) is available the Web UI shows this message instead of the selection in the form:

> No internal Certificate Authorities have been defined. An internal CA must be defined in order to create an internal certificate. Create an internal CA. 

If "Save" is used to "Create an Internal Certificate" an error message is shown to the user and no certificate is created:

> 🔴 The field Certificate authority is required.

The Ansible task should also fail if this requirement is not fulfilled.

**Playbook**
Please paste a minimal playbook to reproduce the issue:
```
- name: VPN CA certificate
  pfsensible.core.pfsense_ca:
    name: "name of CA with just a certificate that is not internal"
    certificate: "{{  lookup('ansible.builtin.file', 'certificiate_authority.crt') }}"
    state: present

- name: User certificates
  pfsensible.core.pfsense_cert:
    name: Test
    ca: "name of CA with just a certificate that is not internal"
    certtype: user
    method: internal
    state: present
```

**Environment**
- What version of pfsensible.core? 0.6.1
- What version of ansible? 10.7.0
- What version of pfSense? 2.7.2-RELEASE

**Additional Information**
The XML of a created user looks like this after a successful call:

```xml
                <cert>
                        <descr>raap</descr>
                        <caref>679b5e7ece02f</caref>
                        <refid>679b5e83adadf</refid>
                        </cert>
```
The elements `type`, `crt`  and `prv` are missing.
