### ISSUE TITLE
[pfsense_aggregate] purge not happening

### ISSUE THREAD

**Issue by santilococo** [pfsensible/core#175]
**Describe the bug**
When using the `pfsense_aggregate` module with the `purge_*` parameter, no action (purge) is performed.

**Expected behavior**
The module should remove any rules that are not defined in the `aggregate_*` lists.

**Playbook**
```
---
...
- name: Set pfSense firewall rules
  pfsensible.core.pfsense_aggregate:
    purge_rules: true
    purge_rule_separators: true
    purge_aliases: true
    aggregated_aliases:
      - { name: port_ssh, type: port, address: 22, state: present }
      - { name: port_http, type: port, address: 80, state: present }
      - { name: port_https, type: port, address: 443, state: present }
    aggregated_rule_separators:
      - { name: "Anti-Lockout", interface: lan, state: present, before: "Anti-Lockout rule (HTTP)" }
      - { name: "Default", interface: lan, state: present, before: "Default allow LAN to any rule" }
    aggregated_rules:
      - { name: "Anti-Lockout rule (HTTP)", action: "pass", interface: "lan", ipprotocol: "inet46", protocol: "tcp", source: "any", destination: "IP:lan", destination_port: "port_http", after: "top", state: "present" }
      - { name: "Anti-Lockout rule (HTTPS)", action: "pass", interface: "lan", ipprotocol: "inet46", protocol: "tcp", source: "any", destination: "IP:lan", destination_port: "port_https", after: "Anti-Lockout rule (HTTP)", state: "present" }
      - { name: "Anti-Lockout rule (SSH)", action: "pass", interface: "lan", ipprotocol: "inet46", protocol: "tcp", source: "any", destination: "IP:lan", destination_port: "port_ssh", after: "Anti-Lockout rule (HTTPS)", state: "present" }
      - { name: "Default allow LAN to any rule", action: "pass", interface: "lan", ipprotocol: "inet46", protocol: "any", source: "NET:lan", destination: "any", after: "Anti-Lockout rule (SSH)", state: "present" }
      - { name: "Default allow any to any rule", action: "pass", interface: "lan", ipprotocol: "inet", protocol: "any", source: "any", destination: "any", after: "Default allow LAN to any rule", state: "present" }
```

**Output**
```
TASK [pfsense_configuration : Set pfSense firewall rules] **********************
task path: /runner/requirements_roles/pfsense_configuration/tasks/rules.yml:2
ok: [pfsense] => {"changed": false, "result_aliases": [], "result_interfaces": [], "result_nat_outbounds": [], "result_nat_port_forwards": [], "result_rule_separators": [], "result_rules": [], "result_vlans": [],
"stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

**Environment**
- What version of pfsensible.core? 0.6.2
- What version of ansible? 2.15.13
- What version of pfSense? 2.7.2-RELEASE (amd64) 

**Additional context**
Here are the relevant parts of `config.xml`:
```
<?xml version='1.0' encoding='us-ascii'?>
<pfsense>
	<version>23.3</version>
	<filter>
		<rule>
			<descr>Anti-Lockout rule (HTTP)</descr>
			<interface>lan</interface>
			<type>pass</type>
			<ipprotocol>inet46</ipprotocol>
			<statetype>keep state</statetype>
			<source>
				<any></any>
			</source>
			<destination>
				<network>lanip</network>
				<port>port_http</port>
			</destination>
			<protocol>tcp</protocol>
			<id></id>
			<tracker>1741002884</tracker>
			<created>
				<time>1741002884</time>
				<username>root</username>
			</created>
			<updated>
				<time>1741003676</time>
				<username>root</username>
			</updated>
		</rule>
		<rule>
			<descr>Anti-Lockout rule (HTTPS)</descr>
			<interface>lan</interface>
			<type>pass</type>
			<ipprotocol>inet46</ipprotocol>
			<statetype>keep state</statetype>
			<source>
				<any></any>
			</source>
			<destination>
				<network>lanip</network>
				<port>port_https</port>
			</destination>
			<protocol>tcp</protocol>
			<id></id>
			<tracker>1741002885</tracker>
			<created>
				<time>1741002884</time>
				<username>root</username>
			</created>
			<updated>
				<time>1741002884</time>
				<username>root</username>
			</updated>
		</rule>
		<rule>
			<descr>Anti-Lockout rule (SSH)</descr>
			<interface>lan</interface>
			<type>pass</type>
			<ipprotocol>inet46</ipprotocol>
			<statetype>keep state</statetype>
			<source>
				<any></any>
			</source>
			<destination>
				<network>lanip</network>
				<port>port_ssh</port>
			</destination>
			<protocol>tcp</protocol>
			<id></id>
			<tracker>1741002886</tracker>
			<created>
				<time>1741002884</time>
				<username>root</username>
			</created>
			<updated>
				<time>1741003676</time>
				<username>root</username>
			</updated>
		</rule>
		<rule>
			<id></id>
			<tracker>0100000101</tracker>
			<type>pass</type>
			<interface>lan</interface>
			<ipprotocol>inet46</ipprotocol>
			<tag></tag>
			<tagged></tagged>
			<max></max>
			<max-src-nodes></max-src-nodes>
			<max-src-conn></max-src-conn>
			<max-src-states></max-src-states>
			<statetimeout></statetimeout>
			<statetype>keep state</statetype>
			<os></os>
			<source>
				<network>lan</network>
			</source>
			<destination>
				<any></any>
			</destination>
			<descr>Default allow LAN to any rule</descr>
			<updated>
				<time>1741002884</time>
				<username>root</username>
			</updated>
		</rule>
		<rule>
			<descr>Default allow any to any rule</descr>
			<interface>lan</interface>
			<type>pass</type>
			<ipprotocol>inet</ipprotocol>
			<statetype>keep state</statetype>
			<source>
				<any></any>
			</source>
			<destination>
				<any></any>
			</destination>
			<id></id>
			<tracker>1739886900</tracker>
			<created>
				<time>1739886900</time>
				<username>root</username>
			</created>
			<updated>
				<time>1741002884</time>
				<username>root</username>
			</updated>
		</rule>
		<rule>
			<id></id>
			<tracker>0100000102</tracker>
			<type>pass</type>
			<interface>lan</interface>
			<ipprotocol>inet6</ipprotocol>
			<tag></tag>
			<tagged></tagged>
			<max></max>
			<max-src-nodes></max-src-nodes>
			<max-src-conn></max-src-conn>
			<max-src-states></max-src-states>
			<statetimeout></statetimeout>
			<statetype>keep state</statetype>
			<os></os>
			<source>
				<network>lan</network>
			</source>
			<destination>
				<any></any>
			</destination>
			<descr>Default allow LAN IPv6 to any rule</descr>
			<updated>
				<time>1739889527</time>
				<username>root</username>
			</updated>
		</rule>
		<rule>
			<id></id>
			<tracker>1740995427</tracker>
			<type>pass</type>
			<interface>lan</interface>
			<ipprotocol>inet</ipprotocol>
			<tag></tag>
			<tagged></tagged>
			<max></max>
			<max-src-nodes></max-src-nodes>
			<max-src-conn></max-src-conn>
			<max-src-states></max-src-states>
			<statetimeout></statetimeout>
			<statetype>keep state</statetype>
			<os></os>
			<protocol>tcp</protocol>
			<source>
				<any></any>
			</source>
			<destination>
				<any></any>
			</destination>
			<descr>Test</descr>
			<updated>
				<time>1740995427</time>
				<username>root</username>
			</updated>
			<created>
				<time>1740995427</time>
				<username>root</username>
			</created>
		</rule>
		<rule>
			<id></id>
			<tracker>1740995894</tracker>
			<type>pass</type>
			<interface>lan</interface>
			<ipprotocol>inet6</ipprotocol>
			<tag></tag>
			<tagged></tagged>
			<max></max>
			<max-src-nodes></max-src-nodes>
			<max-src-conn></max-src-conn>
			<max-src-states></max-src-states>
			<statetimeout></statetimeout>
			<statetype>keep state</statetype>
			<os></os>
			<protocol>tcp</protocol>
			<source>
				<network>lanip</network>
			</source>
			<destination>
				<any></any>
			</destination>
			<descr>new test</descr>
			<updated>
				<time>1740995894</time>
				<username>root</username>
			</updated>
			<created>
				<time>1740995894</time>
				<username>root</username>
			</created>
			<disabled></disabled>
		</rule>
		<separator>
			<lan><sep0>
			<text>Ani-Lockout</text>
			<if>lan</if>
			<color>bg-info</color>
			<row>fr0</row>
			</sep0>
		<sep1>
			<text>Default</text>
			<if>lan</if>
			<color>bg-info</color>
			<row>fr3</row>
			</sep1>
		<sep2>
			<text>Anti-Lockout</text>
			<if>lan</if>
			<color>bg-info</color>
			<row>fr0</row>
			</sep2>
		</lan>
		</separator>
	</filter>
	<aliases>
		<alias>
			<name>port_ssh</name>
			<type>port</type>
			<address>22</address>
			<descr></descr>
			<detail></detail>
		</alias>
		<alias>
			<name>port_http</name>
			<type>port</type>
			<address>80</address>
			<descr></descr>
			<detail></detail>
		</alias>
		<alias>
			<name>port_https</name>
			<type>port</type>
			<address>443</address>
			<descr></descr>
			<detail></detail>
		</alias>
	</aliases>
</pfsense>
```
From this, you can see the "extra" rules that should be removed but aren't.
