### ISSUE TITLE
What am I doing wrong with aggregate configuration? (nothing changed when executed)

### ISSUE THREAD

**Issue by Filmtangent** [pfsensible/core#177]
I seem to be having an issue with aggregate configuration. 

I have set up the various parts of the definitions as per the examples, however, when I run the task, nothing is changed and the returned dict doesn't seem to include any of my changes. 

here is the contents of my definitions.yaml:
```
pfsenses:
  chi_pfsense:
    interfaces: {AWS_DX: {ip: 10.1.0.11/31}}

hosts_aliases:
  chi_lan: {ip: 10.20.36.0/16}
  subnets: {ip: 10.2.6.0/24 10.20.7.0/24 10.2.8.0/24}

ports_aliases:
  port_access:
    {
      port: <ports>,
    }

rules:
  options: { log: yes }
  AWS_DX:
    rule1: { src: subnets, dst: chi_lan, protocol: tcp/udp, dst_port: port_access }
```

this is the result of the run:

```
TASK [Gathering Facts] *********************************************************
task path: /runner/project/firewall.yaml:2
ok: [chi_pfsense]
TASK [Setup common rules and aliases] ******************************************
task path: /runner/project/firewall.yaml:8
ok: [chi_pfsense] => {"changed": false, "result_aliases": [], "result_interfaces": [], "result_nat_outbounds": [], "result_nat_port_forwards": [], "result_rule_separators": [], "result_rules": [], "result_vlans": [], "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
PLAY RECAP *********************************************************************
chi_pfsense                : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
```
{
  "result_aliases": [],
  "result_interfaces": [],
  "result_nat_outbounds": [],
  "result_nat_port_forwards": [],
  "result_rules": [],
  "result_rule_separators": [],
  "result_vlans": [],
  "changed": false,
  "stdout": "",
  "stderr": "",
  "invocation": {
    "module_args": {
      "aggregated_aliases": [],
      "aggregated_rules": [],
      "order_rules": false,
      "purge_aliases": false,
      "purge_interfaces": false,
      "purge_nat_outbounds": false,
      "purge_nat_port_forwards": false,
      "purge_rules": false,
      "purge_rule_separators": false,
      "purge_vlans": false,
      "ignored_aliases": [],
      "ignored_rules": [],
      "aggregated_interfaces": null,
      "aggregated_nat_outbounds": null,
      "aggregated_nat_port_forwards": null,
      "aggregated_rule_separators": null,
      "aggregated_vlans": null,
      "interface_filter": null
    }
  },
  "stdout_lines": [],
  "stderr_lines": [],
  "_ansible_no_log": false
}
```

the hostname of the pfsense (not sure if this is necessary), the host in the inventory and the pfsense in the definition are all the same. 

The playbook itself is as follows:

```
---
- hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.11
    params: "{{ lookup('pfsense', 'lookup_plugins/definitions.yaml', 'all_definitions') }}"
  tasks:
    - name: Setup common rules and aliases
      pfsensible.core.pfsense_aggregate:
        aggregated_aliases: "{{ params['aggregated_aliases'] }}"
        aggregated_rules: "{{ params['aggregated_rules'] }}"
```

any help would be much appreciated!
