### ISSUE TITLE
Missing support for DHGROUP 31 and 32 (P1 and P2)

### ISSUE THREAD

**Issue by DjaFyh** [pfsensible/core#183]
**Describe the bug**
PFSense 2.7 supports for IPSEC P1 and P2, DH GROUPS 31, 32.
PFSensible stops at DH 30

**Expected behavior**
DH 31 and 32 should be usable

**Playbook**
Please paste a minimal playbook to reproduce the issue:
```
vpn:
          p1:
            ...
            encryptionDh: 31
            ...
          p2:
            - ...
              encryptionDh: 31
```

**Output**
Please paste the ansible output run with `-vv`:
```
...
"msg": "value of dhgroup must be one of: 1, 2, 5, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 28, 29, 30, got: 31",
...
```

**Environment**
- What version of pfsensible.core? 0.6.2
- What version of ansible? 2.17.8
- What version of pfSense? 2.7.2

**Additional context**
