### ISSUE TITLE
Auto created VTI Interface Gateway does not exist

### ISSUE THREAD

**Issue by spali** [pfsensible/core#20]
PFSense 2.5.0 with current master of this repo.

A IPSec VTI Interface created with the name `MY_VPN_INTERFACE` automatically creates a gateway `MY_VPN_INTERFACE_VTIV4`.
I can't use this gateway in a `pfsense_route`.
Getting:
```
The gateway Interface MY_VPN_INTERFACE_VTIV4 Gateway does not exist
```
I assume it's similar to #8.

**Comment by f-bor** [comment]
The error message is weird. It should be
`The gateway MY_VPN_INTERFACE_VTIV4 does not exist`

Can you check the task settings from your playbook ?

**Comment by spali** [comment]
Ok, sorry after retry with the example names above, it's now the expected error message.
Must have messed up something else before.

```yaml
- name: "IPSec VTI: {{ network_local_site.name }} - {{ network_remote_site.name }}"
  pfsensible.core.pfsense_interface:
    descr: "MY_VPN_INTERFACE"
    state: present
    enable: True
    interface: "ipsec"

- name: "IPSec Route: {{ network_local_site.name }} - {{ network_remote_site.name }}"
  pfsensible.core.pfsense_route:
    descr: "VPN: {{ network_remote_site.name }} [ANSIBLE MANAGED]"
    state: present
    disabled: False
    network: "{{ network_remote_site.cidr }}"
    gateway: "MY_VPN_INTERFACE_VTIV4"
```
Auto created Gateway after `pfsensible.core.pfsense_interface`.
![image](https://user-images.githubusercontent.com/1839708/110291947-ccce1780-7fec-11eb-8fcf-87d1de78434e.png)

error of `pfsensible.core.pfsense_route`
```
fatal: [redacted_Hostname]: FAILED! => {"changed": false, "msg": "The gateway MY_VPN_INTERFACE_VTIV4 does not exist"}
```

What confuses me... that newly created ipsec tunnels in PFSense 2.5.0 creates not the ipsecXXXX interfaces anymore. I have now only an `ipsec` interface... maybe 2.5.0 has still some ipsec bugs even patched with some of the known ipsec fixes. I do not understand how this will work with multiple new tunnels regarding the same interface name, but cant test that currently.

**Comment by spali** [comment]
I reverted back to 2.4. There at least I get numbered ipsec interfaces. But same error, that the generated gateway does not exist.

Side question:
Any idea how to get the created ipsec interface name in a predictable way from the created VTI P2?

**Comment by spali** [comment]
hope this is a acceptable solution for you.

**Comment by f-bor** [comment]
I have added the two following commits to the upstream repository to solve your issues:
- [c64fd7c](https://github.com/opoplawski/ansible-pfsense/commit/c64fd7c0f40f875d2eb34b22365fefe1db14603f)
- [c7fc1c0](https://github.com/opoplawski/ansible-pfsense/commit/c7fc1c0aee8c8bb9214c9c66d17cf978ab976db5)

The first one is equivalent to your PR. The second one allows you to change an interface settings using only descr (interface=None won't trigger any error).

Let me know if it works for you.

**Comment by opoplawski** [comment]
I've pushed these to this repo so you can test.

**Comment by spali** [comment]
@opoplawski 
Thanks, but I don't get it. Maybe I didn't understand your change. 
But if I'm right, I can't "assign" the interface with your change. Because it has to already exist with the description. 

My change supported to create ("Assign" in GUI) an interface `ipsecXXXX` by it's description (description of the ipsecXXXX, not the "instance" created during assign") which is predictable by the VTI P1 descr. After creating the P2 the interface is by default unassigned and has the description of `IPsec VTI: <descr of P1>`.
So I don't get it to work currently without manually assign the interface in the GUI. Then I can change the options of the assigned interface by descr with your change. But I can't "assign" it with your change.

Here an example, with your change, when the interface is assigned, I can change it with `descr_of_the_assigned_interface`. 
With my change, I could reference the underlying interface `descr_of_the_underlying_ipsecXXXX_interface` to assign (create) the interface `descr_of_the_assigned_interface`
```
  pfsensible.core.pfsense_interface:
    descr: "{{ descr_of_the_assigned_interface }}"
    state: present
    enable: True
    interface:
    interface: "{{ descr_of_the_underlying_ipsecXXXX_interface }}"
```

Hope this is clear enough, otherwise don't hesitate to ask.
