### ISSUE TITLE
pfsensible.core.pfsense_rule does not support urltable_ports alias

### ISSUE THREAD

**Issue by ShaBangBinBash** [pfsensible/core#31]
When defining a firewall rule:
- using a regular alias for source, destination, source port, destination port works
- using a urltable for source, destination works
- using a urltable_ports for source ports, destination ports fails with message
  - "msg": "Cannot parse port ANS_Google_urltable_ports, not port number or alias"

To reproduce, define an URL Table (Ports) and use it in a pfsensible.core.pfsense_rule

example yaml:
```
pfsensible.core.pfsense_rule:
  name: "Title"
  action: "pass"
  interface: "LAN"
  ipprotocol "inet"
  protocol: "tcp/udp"
  source: "NET:LAN"
  destination: "8.8.8.8"
  destination_port: "Google_urltable_ports" # this fails
  state: present
```

I have verified in my testing that my URL Table (Ports) is valid by using it in a rule defined in the web interface of the pfSense
