### ISSUE TITLE
Cant renew admin password

### ISSUE THREAD

**Issue by stefanfluit** [pfsensible/core#33]
Hi, is it possible to use this role to edit the default password?

I'm trying to do so:

```
- name: Change password for admin user
  pfsensible.core.pfsense_user:
    name: "admin"
    descr: "Admin"
    password: "{{ 'PasSw0rd123' | password_hash('bcrypt') }}"
    scope: "user"
    groups: [ 'admins' ]
    priv: [ 'page-all', 'user-shell-access' ]
  when: netgate_configuration
```

But it doesn't affect the password..
