### ISSUE TITLE
is it possible that rules are created in the same order as defined in the playbook?

### ISSUE THREAD

**Issue by pescobar** [pfsensible/core#5]
Hi,

I tried this playbook using ansible `2.9.2` and the collection version `0.2.0`

```
---

- hosts: all

  tasks:

    - name: "Test playbook"
      pfsensible.core.aggregate:
        purge_aliases: true
        purge_rules: true
        purge_rule_separators: true
        aggregated_aliases:
          - { name: ports_http_https, type: port, address: '80 443', state: present }
        aggregated_rules:
          - { name: "rule_1", source: any, destination: any, protocol: any, interface: LAN, state: present, disabled: false }
          - { name: "rule_2", source: any, destination: any, protocol: any, interface: LAN, state: present, disabled: false }
        aggregated_rule_separators:
          - { name: "separator_1", interface: LAN, state: present, before: rule_1 }
          - { name: "separator_2", interface: LAN, state: present, before: rule_2 }
```

and I get this result:

![pfsense_1](https://user-images.githubusercontent.com/103797/73676572-e64bb400-46b4-11ea-91ed-4eddaf76c0df.png)

Then I have updated the playbook adding new rule and separator `rule_0` and `separator_0` combined with `purge_rules` and `purge_separators`:

```
---

- hosts: all

  tasks:

    - name: "Test playbook"
      pfsensible.core.aggregate:
        purge_aliases: true
        purge_rules: true
        purge_rule_separators: true
        aggregated_aliases:
          - { name: ports_http_https, type: port, address: '80 443', state: present }
        aggregated_rules:
          - { name: "rule_0", source: any, destination: any, protocol: any, interface: LAN, state: present, disabled: false }
          - { name: "rule_1", source: any, destination: any, protocol: any, interface: LAN, state: present, disabled: false }
          - { name: "rule_2", source: any, destination: any, protocol: any, interface: LAN, state: present, disabled: false }
        aggregated_rule_separators:
          - { name: "separator_0", interface: LAN, state: present, before: rule_0 }
          - { name: "separator_1", interface: LAN, state: present, before: rule_1 }
          - { name: "separator_2", interface: LAN, state: present, before: rule_2 }
```

and I was expecting that the new rule would appear at the top but it's added at the bottom. see

![pfsense_2](https://user-images.githubusercontent.com/103797/73676608-f368a300-46b4-11ea-9185-504e74faf539.png)

I have seen that module `pfsensible.core.rule` provides the options `before` and `after` to define the order of the rules but if the list of rules grows a lot I would find much more convenient that the order defined in the playbook is respected. Is that possible?

Thanks in advance for any help.
