### ISSUE TITLE
Issues assigning Firewall Rules to Netgate 6100

### ISSUE THREAD

**Issue by defib** [pfsensible/core#50]
I am using pfsense_aggregate with aggregated_rules. The following rules worked for the Netgate 2100, but not the Netgate 6100. Below is a brief example of the code I am running. MANAGEMENT is a VLAN interface on ix0 as: `ix0.100`. 

Task:
```
- name: Setup the Rules
    pfsensible.core.pfsense_aggregate:
      purge_rules: "{{ host_firewall_rules.options.purge_rules }}"
      aggregated_rules: "{{ host_firewall_rules.rules }}"
```

host_vars:

```
host_interfaces:
  management:
    interface: opt8

host_firewall_rules:
  options:
    purge_rules: true
  rules:
    - name: MANAGEMENT - Allow ping out
      state: present
      action: pass
      interface: "{{ host_interfaces.management.interface }}"
      ipprotocol: inet
      protocol: icmp
      source: MANAGEMENTNetwork
      destination: any

```

Ansible is giving me the error:
`mgs: '"opt8" is not a valid interface'`

I have tried `ix0.100`, other opt interfaces. Again this worked on the Netgate 2100. Any ideas or thoughts?
