### ISSUE TITLE
Module interface: "ipv4_type: dhcp" not applied

### ISSUE THREAD

**Issue by aded** [pfsensible/core#6]
Hi,
```
pfsensible.core.interface:
    descr: "..."
    enable: true
    interface: "..."
    ipv4_type: "dhcp"
```
doesn't change the "IPv4 Configuration Type" (it's always "None").
