### ISSUE TITLE
FreeBSD user not added to group

### ISSUE THREAD

**Issue by LeoShivas** [pfsensible/core#70]
Here is my playbook :
```
- name: Create Ansible user on pfSense
  hosts: pfsense
  collections:
    - pfsensible.core
  remote_user: admin
  become: false
  tasks:
    - name: Add Ansible user
      pfsense_user:
        name: "{{ lookup('env','ADM_USR') }}"
        password: "{{ lookup('env','ADM_PWD') | password_hash('bcrypt') }}"
        authorizedkeys: "{{ lookup('env','PUBLIC_KEY') }}"
        descr: Ansible User
        scope: system
        groups: [ 'admins' ]
        priv: [ 'page-all', 'user-shell-access' ]
```

Here is the result :
```
Run ansible-playbook ansible/playbook-pfsense-create-ansible-user.yml
  ansible-playbook ansible/playbook-pfsense-create-ansible-user.yml
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python[2](https://github.com/LeoShivas/ovhbaremetal/actions/runs/5039174203/jobs/9037140620#step:6:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/LeoShivas/ovhbaremetal/actions/runs/5039174203/jobs/9037140620#step:6:3).11.3/x6[4](https://github.com/LeoShivas/ovhbaremetal/actions/runs/5039174203/jobs/9037140620#step:6:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x[6](https://github.com/LeoShivas/ovhbaremetal/actions/runs/5039174203/jobs/9037140620#step:6:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[11](https://github.com/LeoShivas/ovhbaremetal/actions/runs/5039174203/jobs/9037140620#step:6:11).3/x64/lib
    ADM_USR: ***
    ADM_PWD: ***
    PUBLIC_KEY: ***
  

PLAY [Create Ansible user on pfSense] ******************************************

TASK [Gathering Facts] *********************************************************
ok: [pfsense.jordan-lenuff.com]

TASK [Add Ansible user] ********************************************************
changed: [pfsense]

PLAY RECAP *********************************************************************
pfsense  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

When I go to the pfSense web GUI, I can see my new created user :
![image](https://github.com/pfsensible/core/assets/28844182/9fbe60d2-e447-43da-a92d-57947cdde35f)

When I log through SSH into the server, I can see the FreeBSD created user :
```
[2.6.0-RELEASE][admin@pfSense.home.arpa]/root: id myuser
uid=2000(myuser) gid=65534(nobody) groups=65534(nobody)
[2.6.0-RELEASE][admin@pfSense.home.arpa]/root:
```

But, as shown above, the user does not belong to the `admins` group.

I tried to manually delete the `/tmp/config.cache` file, run some of the rc scripts (as `/etc/rc.restart_webgui`, `/etc/rc.reload_all`, etc ...), but nothing updates the user groups.

If I simply reboot the pfSense machine, the user finally belongs to the `admins`.

So, I have to questions :
- How can I update the FreeBSD user groups without rebooting ?
- Can the pfsensible module can be updated to do it automatically ?
