### ISSUE TITLE
Unable to implement Invert Match in Rules 

### ISSUE THREAD

**Issue by IvanDaich** [pfsensible/core#75]
Hi all, thank you for putting together these modules. 

I'm working on a project for importing bulk rules into a new firewall I'm building and I've been able to troubleshoot most things but I'm having a hard time using one small feature. I cannot get the pfsense_rules modules to add the "Invert Match" for source/destination addresses. 

The playbook task compiles and it creates the rule I want but it simply omits the Invert Match. The documentation states that "the destination/source address, in [!]{IP,HOST,ALIAS,any,(self),IP:INTERFACE,NET:INTERFACE} format." So I included in the rule field "destination: ! Alias_Name". This compiled and creates the rule but it skips the Invert Match.

So I've tried any syntax possibility I could think of. I've tried other permutations with and without spaces, any combination of parenthesis, braces, and brackets. Some examples are:

destination: [!] Alias_Name
destination: [!] {Alias_Name}
destination: [!] (Alias_Name)
destination: "!" Alias_Name
destination: '!' Alias_Name

I don't want to point fingers and say that the function is bugged, so can someone point me to what I'm doing wrong? If I'm not, is this something that could be easily patched and pushed?

**Comment by f-bor** [comment]
Hello Ivan, what version of pfSense is installed on the target firewall ?

**Comment by f-bor** [comment]
I did a test on a 2.7.0 and it worked as expected (I don't have a 2.6.0 ready). Here is my task setup:
```
    - name: "test rule"
      pfsensible.core.pfsense_rule:
        action: pass
        destination: "!test_alias"
        source: "!test_alias"
        protocol: any
        name: test
        interface: test_199
```

Can you share your playbook ?
