### ISSUE TITLE
Module route: "The gateway XYZ does not exist"

### ISSUE THREAD

**Issue by aded** [pfsensible/core#8]
When an interface is manually configured with DHCP, the correspondent gateway is automatically added (let's say its name is XYZ_DHCP).
But when trying to configure a route:
```
pfsensible.core.route:
    descr:   "..."
    gateway: "XYZ_DHCP"
    network: "192.168.0.0/24"
```
I get the error: "The gateway XYZ_DHCP does not exist".
