### ISSUE TITLE
pfsense_dhcp_static: No DHCP configuration found for netif

### ISSUE THREAD

**Issue by J1810Z** [pfsensible/core#94]
I am not able to set a static dhcp entry.

pfSense Version: 
2.6.0-RELEASE

Ansible Playbook:
```
- hosts: pfsense
  remote_user: ansible
  vars:
    ansible_ssh_private_key_file: "/path_to_rsa/id_rsa_ansible"
  tasks:
  - name: Create DHCP static mapping
    pfsensible.core.pfsense_dhcp_static:
      name: "test"
      macaddr: "8a:8d:7f:08:77:a1"
      ipaddr: "192.168.100.10"
      state: present
      netif: "MAINNET"
```

Output:
```
TASK [Create DHCP static mapping] 
fatal: [192.168.x.x]: FAILED! => {"changed": false, "msg": "No DHCP configuration found for netif='MAINNET'"}
```

**Comment by RobertHolstein** [comment]
Same issue here. 

2.7.0-RELEASE (amd64)

```
  - name: Create DHCP static mapping
    pfsensible.core.pfsense_dhcp_static:
      name: "robertphone"
      hostname: "robertphone"
      macaddr: "c4:98:80:59:95:68"
      ipaddr: "10.0.150.222"
      netif: "WIFI"
      state: present
```

```
TASK [Create DHCP static mapping] *****************************************************************
fatal: [pfsense]: FAILED! => {"changed": false, "msg": "No DHCP configuration found for netif='WIFI'"}
```

**Comment by RobertHolstein** [comment]
I actually just figured it out while looking at the XML backup of my firewall rules. The backup has all my vlans named opt[n]. 

```
	<separator>
		<opt1></opt1>
		<opt2></opt2>
		<opt3></opt3>
		<opt4></opt4>
		<opt5></opt5>
		<lan></lan>
		<wan></wan>
	</separator>
```

I know WIFI is the first vlan I created so I used `opt1` and the task succeeded.
```
    - name: Create DHCP static mapping
      pfsensible.core.pfsense_dhcp_static:
        name: "robertphone"
        hostname: "robertphone"
        macaddr: "c4:98:80:59:95:68"
        ipaddr: "10.0.150.222"
        netif: "opt1"
        state: present
```
<img width="865" alt="image" src="https://github.com/pfsensible/core/assets/22876269/3741ba47-3872-40e7-a1c4-f2c7458d909a">
